#!/usr/bin/env python3
"""One-off regeneration of existing signal_report_*.md files into the new nested
hour -> run -> per-market-table format that src/report.rs now writes going forward.

Historical run blocks (each a top-level `<details open>...</details>`) are parsed out of
the old flat file with the same depth-counted `<details>`/`</details>` matching report.rs
uses at runtime, their trade rows are pulled straight out of the old combined
"#### Trades (past hour)" table (which already has every column needed — datetime, market,
variant, side, outcome, pnl), regrouped into one collapsible table per market, and the
non-trade tail (crypto/weather/worldcup snapshots, staleness, cpu) is kept verbatim.
Consecutive runs sharing the same "{date} {HH}:00" label (always contiguous, since runs are
always prepended newest-first) are nested under one shared hour `<details>`, matching the
new format's marker conventions (`<!-- siglab-hour:... -->` etc.) so the live process can
keep extending the current hour on its very next write instead of starting fresh.

Caveat: pre-2026-07-13 cadence was hourly, so each hour genuinely had one run. After the
2026-07-13 21:xx HKT cadence change to 15 min, a real hour can have several runs — but the
original per-run summary line only ever recorded "{date} {HH}:00" (never the real minute),
so multiple runs within the same hour are indistinguishable here beyond their order in the
file. This script does not fabricate fake :15/:30/:45 labels for them.
"""

import re
import sys
from pathlib import Path

HEADER_TEMPLATE = """# siglab signal report — {date}

Auto-generated by siglab, newest hour first — each hour is one collapsible section
containing every report-writer run that landed within it, and each run's trades are
broken out into one collapsible table per market. See
`siglab/doc/local_resource_test_2026-07-13.md` for the Docker resource baseline and
`siglab/doc/plan_weather_worldcup_trading_2026-07-13.md` for what this harness does
and does not claim. Weather and World Cup markets trade via a self-contained
`bucket_reversal.rs` reversal engine (18 variants per bucket, no delta/Gamma/resolve —
see that file's doc comment), separate from crypto's `trader::machine::Machine`.

"""

HOUR_MARKER_PREFIX = "<!-- siglab-hour:"
HOUR_BODY_START = "<!-- siglab-hour-body-start -->\n"
HOUR_BODY_END = "<!-- siglab-hour-body-end -->\n"
RUN_MARKER = "<!-- siglab-run -->\n"

RUN_SUMMARY_RE = re.compile(
    r"<summary><strong>(?P<date>\d{4}-\d{2}-\d{2}) (?P<hour>\d{2}):00 HKT — .*?</strong></summary>"
)
TRADE_ROW_RE = re.compile(
    r"^\| (?P<dt>[^|]+?) \| (?P<market>[^|]+?) \| (?P<variant>[^|]+?) \| "
    r"(?P<side>[^|]+?) \| (?P<outcome>[^|]+?) \| (?P<pnl>[^|]+?) \|$"
)


def matching_details_close(s: str, open_pos: int) -> int:
    """Byte offset one past the `</details>` that closes the `<details...>` tag starting
    at `open_pos`, using the same depth-counted match report.rs's runtime logic relies on
    (via explicit markers there; here via generic bracket-matching since the old files
    predate those markers)."""
    events = []
    for m in re.finditer(r"<details(?: open)?>", s[open_pos:]):
        events.append((m.start(), 1, m.end()))
    for m in re.finditer(r"</details>", s[open_pos:]):
        events.append((m.start(), -1, m.end()))
    events.sort(key=lambda e: e[0])
    depth = 0
    for pos, delta, end in events:
        depth += delta
        if depth == 0 and delta == -1:
            return open_pos + end
    raise ValueError(f"unbalanced <details> starting at {open_pos}")


def parse_old_runs(body: str):
    """Yields (date, hour, summary_line, trade_rows, tail_html) for each old top-level run
    block, in file order (newest first)."""
    for m in re.finditer(r"<details open>\n", body):
        start = m.start()
        end = matching_details_close(body, start)
        block = body[start:end]

        summary_m = RUN_SUMMARY_RE.search(block)
        if not summary_m:
            raise ValueError(f"run block at {start} has no parseable summary line")
        date, hour = summary_m.group("date"), summary_m.group("hour")
        summary_line = block[
            block.index("<summary>") : block.index("</summary>") + len("</summary>")
        ]

        rows = []
        for line in block.splitlines():
            row_m = TRADE_ROW_RE.match(line.strip())
            if row_m and row_m.group("dt") != "datetime (HKT)":
                rows.append(row_m.groupdict())

        # Tail = everything from the first nested "Crypto market state snapshot" details
        # onward, up to (not including) this block's own closing "</details>\n</details>".
        tail_start = block.index("<details>\n<summary>Crypto market state snapshot")
        tail = block[tail_start:]
        # Strip this run's own two trailing closes (CPU section's + the outer wrapper's).
        assert tail.rstrip().endswith("</details>\n\n</details>")
        tail = tail.rstrip()[: -len("\n\n</details>")] + "\n\n"

        yield date, hour, summary_line, rows, tail


def render_market_table(rows):
    out = "| datetime (HKT) | variant | side | outcome | pnl |\n|---|---|---|---|---|\n"
    for r in sorted(rows, key=lambda r: r["dt"]):
        out += f"| {r['dt']} | {r['variant']} | {r['side']} | {r['outcome']} | {r['pnl']} |\n"
    return out + "\n"


def render_trade_summary(rows):
    agg = {}
    for r in rows:
        key = (r["market"], "reversal")  # every trade in these logs is "reversal"
        c, total = agg.get(key, (0, 0.0))
        agg[key] = (c + 1, total + float(r["pnl"]))
    out = "#### Summary: PnL by market and strategy\n\n"
    out += "| market | strategy | trades | total pnl |\n|---|---|---|---|\n"
    for (market, strategy), (count, total) in sorted(agg.items()):
        out += f"| {market} | {strategy} | {count} | {total:.4f} |\n"
    grand_total = sum(float(r["pnl"]) for r in rows) + 0.0
    out += f"\n**Total pnl: {grand_total:.4f}**\n\n"
    return out


def render_trades_section(rows, label):
    out = f"<details>\n<summary>Trades ({label}): {len(rows)} trade(s)</summary>\n\n"
    if not rows:
        return out + "_No trades fired._\n\n</details>\n\n"
    out += render_trade_summary(rows)
    by_market = {}
    for r in rows:
        by_market.setdefault(r["market"], []).append(r)
    for market in sorted(by_market):
        market_rows = by_market[market]
        pnl = sum(float(r["pnl"]) for r in market_rows) + 0.0
        label_m = market if market else "(unknown market)"
        out += f"<details>\n<summary>{label_m} — {len(market_rows)} trade(s), total pnl {pnl:.4f}</summary>\n\n"
        out += render_market_table(market_rows)
        out += "</details>\n\n"
    out += "</details>\n\n"
    return out


def render_run_block(summary_line, rows, tail):
    out = f"<details>\n{summary_line}\n\n"
    out += render_trades_section(rows, "past hour")
    out += tail
    out += "</details>\n\n"
    return out


def render_hour_block(date, hour, run_blocks, all_rows, is_latest):
    hour_key = f"{date}T{hour}"
    hour_label = f"{date} {hour}:00"
    open_attr = " open" if is_latest else ""
    pnl = sum(float(r["pnl"]) for r in all_rows) + 0.0
    inner = "".join(RUN_MARKER + rb for rb in run_blocks)
    return (
        f"{HOUR_MARKER_PREFIX}{hour_key} -->\n"
        f"<details{open_attr}>\n"
        f"<summary><strong>{hour_label} HKT — {len(run_blocks)} report run(s), "
        f"{len(all_rows)} trade(s) this hour, total pnl {pnl:.4f}</strong></summary>\n\n"
        f"{HOUR_BODY_START}"
        f"{inner}"
        f"{HOUR_BODY_END}"
        f"</details>\n\n"
    )


def regenerate(path: Path):
    text = path.read_text()
    first_details = text.index("<details")
    body = text[first_details:]

    runs = list(parse_old_runs(body))
    if not runs:
        print(f"  {path.name}: no run blocks found, skipping")
        return

    # Group consecutive runs sharing the same (date, hour) — always contiguous by
    # construction (runs are always prepended newest-first).
    groups = []
    for date, hour, summary_line, rows, tail in runs:
        run_block = render_run_block(summary_line, rows, tail)
        if groups and groups[-1][0] == (date, hour):
            groups[-1][1].append(run_block)
            groups[-1][2].extend(rows)
        else:
            groups.append(((date, hour), [run_block], list(rows)))

    date0 = runs[0][0]
    header = HEADER_TEMPLATE.format(date=date0)

    out = header
    for i, ((date, hour), run_blocks, all_rows) in enumerate(groups):
        out += render_hour_block(date, hour, run_blocks, all_rows, is_latest=(i == 0))

    path.write_text(out)
    print(f"  {path.name}: {len(runs)} run(s) regrouped into {len(groups)} hour section(s)")


def main():
    report_dir = Path(__file__).resolve().parent.parent / "doc" / "report"
    files = sorted(report_dir.glob("signal_report_*.md"))
    if not files:
        print("no signal_report_*.md files found", file=sys.stderr)
        sys.exit(1)
    for f in files:
        regenerate(f)


if __name__ == "__main__":
    main()
